version: '3'                                                                                                                                                             

networks:
  databus:
    external:
      name: databus
  database:
    external:
      name: database
volumes:
  pgconfig:
    external:
      name: pgconfig
  pgdata:
    external:
      name: pgdata
  kafkaconfig:
    external:
      name: kafkaconfig
  kafkadata:
    external:
      name: kafkadata
  zookeeperconfig:
    external:
      name: zookeeperconfig
  zookeeperdata:
    external:
      name: zookeeperdata
  
services:                                                                                                                                                                
  db:
    container_name: pgsql
    build: postgresql/
    restart: always
    ports:
      - 5432:5432
    networks:
      - database
    environment:
      - SERVICEUSER=onecversion
      - SERVICEPASSWORD=onecversion
    volumes:
      - pgdata:/var/lib/postgresql/14/main
  zookeeper:                                                                                                                                                             
    container_name: zookeeper                                                                                                                                            
    build: zookeeper/                                                                                                                                                    
    restart: always
    networks:
      - databus
    ports:                                                                                                                                                               
      - 2185:2185                                                                                                                                                        
    volumes:                                                                                                                                                             
      - zookeeperdata:/tmp/zookeeper                                                                                                                                  
  kafka:                                                                                                                                                                 
    container_name: kafka                                                                                                                                                
    build: kafka/  
    restart: always                                                                                                                                                      
    depends_on:                                                                                                                                                          
      - zookeeper  
    networks:
      - databus                                                                                                                                                      
    ports:                                                                                                                                                               
      - 9092:9092                                                                                                                                                        
    volumes:                                                                                                                                                             
      - kafkadata:/tmp/kafka-logs