version: '3'                                                                                                                                                             

networks:                                                                                                                                                                
  default:                                                                                                                                                               
    external:                                                                                                                                                            
      name: kafka    
volumes:
  configuration:
  pg_data:
services:                                                                                                                                                                
  db:
    container_name: postgres
    build: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - SERVICEUSER=onecversion
      - SERVICEPASSWORD=onecversion
    volumes:
     - configuration:/etc/postgresql/14/main
     - pg_data:/var/lib/postgresql/14/main
  # zookeeper:                                                                                                                                                             
  #   container_name: zookeeper                                                                                                                                            
  #   build: zookeeper/                                                                                                                                                    
  #   restart: always
  #   ports:                                                                                                                                                               
  #     - 2185:2185                                                                                                                                                        
  #   volumes:                                                                                                                                                             
  #     - ./zookeeper/conf:/opt/zookeeper/conf                                                                                                                             
  #     - ./zookeeper/data:/tmp/zookeeper                                                                                                                                  
  # kafka:                                                                                                                                                                 
  #   container_name: kafka                                                                                                                                                
  #   build: kafka/  
  #   restart: always                                                                                                                                                      
  #   depends_on:                                                                                                                                                          
  #     - zookeeper                                                                                                                                                        
  #   ports:                                                                                                                                                               
  #     - 9092:9092                                                                                                                                                        
  #   volumes:                                                                                                                                                             
  #     - ./kafka/conf:/opt/kafka/config                                                                                                                                   
  #     - ./kafka/docdata:/tmp/kafka-logs   
